# Generated by Django 4.2.6 on 2023-10-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunkdata',
            old_name='file_id',
            new_name='file',
        ),
    ]
